modules/posts/public/posts.controllers.js
modules/posts/public/posts.services.js
modules/posts/public/views/feed.html
modules/posts/server/controllers/posts.js
modules/posts/server/models/posts.js
modules/posts/server/routes/posts.js
public/css/main.css
public/src/main.scss

Completed like/unlike and count of likes on posts.

Liking posts

---

index.js
modules/posts/server/controllers/posts.js
modules/posts/server/models/posts.js
modules/posts/server/tests/posts.test.js
package.json
tools/test/mocha-req.js

Testing done for posts backend.

Testing posts backend.

---

modules/posts/public/posts.controllers.js
modules/posts/public/posts.services.js
modules/posts/public/views/feed.html
modules/posts/server/controllers/posts.js
modules/posts/server/models/posts.js
modules/posts/server/routes/posts.js
modules/posts/server/tests/posts.test.js
modules/users/public/users.controllers.js
public/css/main.css
public/src/main.scss

Basic commenting done with tests.

Commenting 101

---

modules/posts/public/posts.routes.js
modules/users/public/users.controllers.js
public/app.js
system/index.js

#42: Allow refresh to stay on same page

---

modules/posts/public/posts.controllers.js
modules/posts/public/posts.routes.js
modules/posts/public/posts.services.js
modules/posts/public/views/feed.html
modules/posts/server/controllers/posts.js
public/css/main.css
public/src/main.scss

Hashtags filterable from feed and timeline

---

package.json
system/public/utils.js

Maintain session over tabs

---

modules/posts/server/controllers/posts.js
modules/users/public/users.js
modules/users/server/controllers/users.js
modules/users/server/models/users.js
public/app.js

#48 Each user to maintain the current login status: loggedIn: true/false.

Online status

---

modules/users/public/users.controllers.js
modules/users/public/views/login.html
modules/users/server/models/users.js

Added username field to be used for mentions

---

modules/posts/public/posts.controllers.js
modules/posts/public/views/feed.html
modules/posts/server/controllers/posts.js
modules/posts/server/models/posts.js
modules/posts/server/tests/posts.test.js

Limited number of comments shown in listing pages (feed and timeline). All comments will be shown in the single item page.

Comments limited as per issue #31

---

modules/posts/public/posts.controllers.js
modules/posts/public/views/feed.html
modules/posts/server/controllers/posts.js
public/css/main.css
public/src/main.scss
system/config/development.js
system/config/production.js

Finished timeline and feed pagination as per issue #19.

Pagination

---

modules/posts/server/controllers/posts.js
modules/users/public/users.controllers.js
modules/users/public/views/profile.html
modules/users/server/controllers/users.js
modules/users/server/routes/users.js
system/public/views/search.html

Can now edit Full name and Designation fields (#17).

Edit profile completed

---

modules/notifications/public/notifications.controllers.js
modules/notifications/public/notifications.js
modules/notifications/public/notifications.services.js
modules/posts/server/models/posts.js
modules/users/public/users.services.js
modules/users/server/controllers/users.js
modules/users/server/models/users.js
modules/users/server/routes/users.js
public/app.js
public/css/main.css
public/index.html
public/src/main.scss
system/config/development.js

In browser notifications done (#18).
Email notifications still pending.

Notifications

---

bower.json
modules/notifications/public/notifications.controllers.js
modules/notifications/public/notifications.js
modules/notifications/public/notifications.services.js
modules/posts/public/posts.controllers.js
modules/posts/public/posts.services.js
modules/posts/public/views/feed.html
modules/posts/server/controllers/posts.js
modules/posts/server/models/posts.js
modules/users/public/users.services.js
modules/users/server/controllers/users.js
modules/users/server/models/users.js
modules/users/server/templates/notification.html
package.json
public/css/main.css
public/index.html
public/src/main.scss
system/config/development.js
system/config/production.js
system/helpers/notifications.js
system/index.js
system/models/settings.js

This PR resolves #18, #56 and #60.

Offline notifications, mentions and emoticons

---

bower.json
modules/posts/public/posts.controllers.js
modules/posts/public/views/feed.html
modules/posts/public/views/post-single.html
modules/streams/public/streams.controllers.js
modules/streams/public/views/streamsList.html
modules/users/public/users.controllers.js
modules/users/public/views/login.html
modules/users/public/views/profile.html
public/css/main.css
public/index.html
public/src/main.scss
system/config/development.js
system/public/index.js

Ng material upgrade

---

modules/users/public/users.controllers.js
modules/users/public/views/profile.html

Added `cancel` button as user may want to cancel editing profile

new: added cancel button while editing profile

---

modules/users/public/users.controllers.js
modules/users/public/users.routes.js
modules/users/public/views/activating.html
modules/users/server/controllers/users.js
modules/users/server/models/users.js
public/app.js
system/helpers/notifications.js

Fixes #16 
P.s.: Worked during the car ride, head spinning now!

Activation email

---

modules/users/public/users.controllers.js
modules/users/public/users.services.js
modules/users/public/views/login.html
modules/users/server/controllers/users.js
modules/users/server/models/users.js
modules/users/server/routes/users.js
public/css/main.css
public/src/main.scss

Fixes #16, adds a better way to resend activation email.

New: Added registration activation functionality

---

modules/users/server/controllers/users.js
package.json
system/config/development.js
system/config/production.js

Upload photo on s3

---

modules/posts/public/posts.controllers.js
modules/posts/public/posts.services.js
modules/posts/public/views/feed.html
modules/posts/public/views/post-single.html
modules/posts/server/controllers/posts.js
modules/posts/server/models/posts.js
modules/posts/server/routes/posts.js
modules/streams/public/views/streamsList.html
modules/users/public/users.controllers.js
modules/users/public/users.services.js
modules/users/public/views/users-dialog.html
modules/users/public/views/users-invite-dialog.html
modules/users/server/controllers/users.js
modules/users/server/routes/users.js
public/css/main.css
public/index.html
public/src/main.scss
system/helpers/notifications.js
system/public/templates/notification.html
system/public/utils.js

Fixed #94 
Fixed #103 
Fixed #93 
Fixed #25

Fixed and Added a lot of stuff here

---

modules/users/public/users.controllers.js
modules/users/public/users.routes.js
modules/users/public/users.services.js
modules/users/public/views/change-password.html
modules/users/public/views/login.html
modules/users/public/views/profile.html
modules/users/public/views/users-pwd-dialog.html
modules/users/server/controllers/users.js
modules/users/server/routes/users.js
public/app.js
system/public/templates/notification.html

Forgot pwd
